version: 0.1

storage:
  filesystem:
    rootdirectory: /var/lib/registry

http:
  addr: 0.0.0.0:5000

auth:
  token:
    realm: http://llh-tencent-os:8888/api/auth
    service: llh-tencent-os:5000
    issuer: 'admin'
    rootcertbundle: /etc/docker/registry/auth.cert