spring:
  application:
    name: zipkin-server
  datasource:
    url: jdbc:mysql://llh-tencent-os:3306/zipkin?allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
    username: root
    password: 1qaz@WSX
    continueOnError: true
    #启动时需要初始化的建表语句
#    schema: classpath:/mysql/zipkin.sql
    #初始化的数据
    data: /mysql/zipkin.sql
    # Initialize the datasource with available DDL and DML scripts.
    initialization-mode: always
    #data-password:
    #data-username:
    #schema-password:
    #schema-username:
    sql-script-encoding: utf-8
    separator: ;

server:
  port: 8083

# eureka注册中心
eureka:
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://root:1qaz2wsx@llh:8761/eureka/
  instance:
    prefer-ip-address: true
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}

security: false
management:
  #去除控制台异常
  metrics.web.server.auto-time-requests: false
  endpoints:
    shutdown:
      enabled: true
    health:
      sensitive: false
      show-details: always
    web:
      exposure:
        include: "*"