server:
  port: 8788

spring:
  dubbo:
    application:
      name: dubbo-producer
    registry:
      address: zookeeper://127.0.0.1:2181                  # zookeeper注册中心的地址
    protocol:
      name: dubbo
      serialization: hessian2
    provider:
      retries: 0                           # 服务调用重试次数，服务发布者不给重试，让服务调用者自己重试