spring:
  application:
    name: eureka-server
  security:
    user:
      name: root
      password: 1qaz2wsx
server:
  port: 8761

eureka:
  server:
    #中小规模下，自我保护模式坑比好处多，所以关闭它
    #是否开启自我保护（运行期间spring会统计信条失败的比例在15分钟之内是否低于85%，如果不低于85%，Eureka会将实例注册信息保护起来，让这些实例不会过期）
    enableSelfPreservation: false
    #心跳阈值计算周期，如果开启自我保护模式，可以改一下这个配置
    renewalThresholdUpdateIntervalMs: 120000
    #主动失效检测间隔,配置成5秒  5秒钟自动剔除失效的节点
    evictionIntervalTimerInMs: 5000
    #禁用readOnlyCacheMap
    useReadOnlyResponseCache: false
  instance:
    hostname: localhost
    ## 心跳间隔，10秒
    leaseRenewalIntervalInSeconds: 10
    ## 没有心跳的淘汰时间，15秒
    leaseExpirationDurationInSeconds: 15
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
    home-page-url-path: /
  client:
    #自己也注册到注册中心
    register-with-eureka: true
    #需要从其他eureka节点获取注册信息
    fetch-registry: false
    serviceUrl:
      defaultZone: http://root:1qaz2wsx@llh:8761/eureka/

security: false
management:
  endpoints:
    shutdown:
        enabled: true
    health:
        sensitive: false
        show-details: always
    web:
      exposure:
        include: "*"