spring:
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: llh:9300
  rocketmq:
    nameServer: llh:9876
    producer:
      group: producer-group

security: false
management:
  endpoints:
    shutdown:
      enabled: true
    health:
      sensitive: false
      show-details: always
    web:
      exposure:
        include: "*"