spring:
  servlet:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 100MB
fdfs:
  soTimeout: 1500
  connectTimeout: 600
  thumbImage:             #缩略图生成参数
    width: 150
    height: 150
  trackerList:            #TrackerList参数,支持多个
    - 10.250.209.43:22122
  pool:
    jmx-enabled: false

security: false
management:
  endpoints:
    shutdown:
      enabled: true
    health:
      sensitive: false
      show-details: always
    web:
      exposure:
        include: "*"