fdfs:
  soTimeout: 1500
  connectTimeout: 600
  thumbImage:             #缩略图生成参数
    width: 150
    height: 150
  trackerList:            #TrackerList参数,支持多个
  - llh-tencent-os:22122

security: false
management:
  endpoints:
    shutdown:
      enabled: true
    health:
      sensitive: false
      show-details: always
    web:
      exposure:
        include: "*"