spring:
  datasource:
    url: jdbc:p6spy:mysql://llh-tencent-os:3306/lvxin-agricultural-trade?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 1qaz@WSX
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
  mvc:
#    static-path-pattern: /**
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  freemarker:
    template-loader-path: /templates
  thymeleaf:
    template-resolver-order: 122
#  redis:
#    cluster:
#      nodes: 10.250.209.89:7000,10.250.209.89:7001,10.250.209.89:7002,10.250.209.89:7003,10.250.209.89:7004,10.250.209.89:7005,10.250.209.89:7006
#      timeout: 2000
#      max-redirects: 7
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  rocketmq:
    name-server: 127.0.0.1:9876
    producer:
      group: producer-group
  p6spy:
    logFile: /home/${spring.application.name}/spy.log


# routes to serviceId
zuul:
  routes:
    fastdfs-server:
      path: /fastdfs/**
      serviceId: fastdfs-server
      stripPrefix: true
    elasticsearch-server:
      path: /elasticsearch/**
      serviceId: elasticsearch-server
      stripPrefix: true
    shiro-server:
      path: /shiro/**
      serviceId: shiro-server
      stripPrefix: true
  ignored-services: '*'
  ignoredPatterns: /**/**/index, /**/**/edit/**, /core/**, /**/**/copy/**, /pdf/*


security: false
management:
  endpoint:
    bus-refresh:
      enabled: true
  endpoints:
    shutdown:
      enabled: true
    health:
      sensitive: false
      show-details: always
    web:
      exposure:
        include: "*"

mybatis:
  mapper-locations: classpath:/mapper/*.xml
#  config-location: classpath:/spring-mybatis-cfg.xml
  typeHandlerPackage: com.lilianghui.framework.mybatis.mapping
  configurationProperties:
    jdbcTypeForNull: OTHER
    mapUnderscoreToCamelCase: true


mapper:
  mappers:
  - com.lilianghui.framework.core.mapper.Mapper
  notEmpty: true
  resolveClass: com.lilianghui.framework.core.mapper.tk.resolve.DefaultEntityResolve

redisson:
  address: 127.0.0.1:6379
  password:

gatway:
  name: llh
  age: 24