spring:
  datasource:
    url: jdbc:p6spy:mysql://llh-tencent-os:3306/lvxin-agricultural-trade?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 1qaz@WSX
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
  mvc:
#    static-path-pattern: /**
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  freemarker:
    template-loader-path: /templates
  thymeleaf:
    template-resolver-order: 122
  shiro:
    loginUrl: /
    successUrl: /success
    unauthorizedUrl: /unauthorized
    cacheName: aa
    hashAlgorithmName: MD5
    hashIterations: 6
    total: 6
    cacheManagerConfigFile: classpath:ehcache/shiro-ehcache.xml
    globalSessionTimeout: 6000
    sessionValidationInterval: 6000
    activeSessionsCacheName: shiroActiveSessionCache
    cookieName: aa
    cipherKey: 4AvVhmFLUs0KTA3Kprsdag==
    rememberMeCookieName: rememberMe
    rememberMeMaxAge: 1
    realms:
      - com.lilianghui.commons.security.UserRealm
    filterChainDefinitionMap:
      '/': 'anon'
      '/login': 'anon'
      '/resources/**': 'anon'
      '/**': 'authc'
    filterChainDefinitionClass: com.lilianghui.commons.security.ChainDefinitionSectionMetaSource
    redisCache:
      shiroActiveSessionCache:
        timeout: 10
#  redis:
#    cluster:
#      nodes: 10.250.209.89:7000,10.250.209.89:7001,10.250.209.89:7002,10.250.209.89:7003,10.250.209.89:7004,10.250.209.89:7005,10.250.209.89:7006
#      timeout: 2000
#      max-redirects: 7
  redis:
    password:
    database: 0
    host: 127.0.0.1
    port: 6379
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1
    timeout: 5000

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  rocketmq:
    nameServer: 127.0.0.1:9876
    producer:
      group: producer-group
  p6spy:
    logFile: /home/${spring.application.name}/spy.log


# routes to serviceId
zuul:
  routes:
    fastdfs-server:
      path: /fastdfs/**
      serviceId: fastdfs-server
      stripPrefix: true
    elasticsearch-server:
      path: /elasticsearch/**
      serviceId: elasticsearch-server
      stripPrefix: true
    shiro-server:
      path: /shiro/**
      serviceId: shiro-server
      stripPrefix: true
  ignored-services: '*'
  ignoredPatterns: /**/**/index, /**/**/edit/**, /core/**, /**/**/copy/**, /pdf/*


security: false
management:
  endpoint:
    bus-refresh:
      enabled: true
  endpoints:
    shutdown:
      enabled: true
    health:
      sensitive: false
      show-details: always
    web:
      exposure:
        include: '*'

mybatis:
  configuration: com.lilianghui.spring.starter.mybatis.MyBatisConfiguration
  mapper-locations: classpath:/mapper/*.xml
  typeHandlersPackage: com.lilianghui.framework.mybatis.mapping
  jdbcTypeForNull: NULL
  mapUnderscoreToCamelCase: true


mapper:
  mappers:
  - com.lilianghui.framework.core.mapper.Mapper
  notEmpty: true
  resolveClass: com.lilianghui.framework.core.mapper.tk.resolve.DefaultEntityResolve
  entityScanPackages: com.lilianghui.entity
  enumerationHandlerClass: com.lilianghui.framework.mybatis.mapping.EnumerationHandler

redisson:
  address: 127.0.0.1:6379
  password:

gatway:
  name: llh
  age: 24