spring:
  datasource:
    url: jdbc:p6spy:mysql://llh-tencent-os:3306/lvxin-agricultural-trade?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
  mvc:
#    static-path-pattern: /**
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  freemarker:
    template-loader-path: /templates
  thymeleaf:
    template-resolver-order: 122
  shiro:
    loginUrl: /
    successUrl: /success
    unauthorizedUrl: /unauthorized
    cacheManagerConfigFile: classpath:ehcache/shiro-ehcache.xml
    #session失效时间 2小时,单位毫秒
    globalSessionTimeout: 7200000
    #session定时清理间隔 30分钟,单位毫秒
    sessionValidationInterval: 1800000
    activeSessionsCacheName: shiroActiveSessionCache
    cookieName: shiroCookie
    cipherKey: 4AvVhmFLUs0KTA3Kprsdag==
    rememberMeCookieName: rememberMeCookie
    #记住我cookie生效时间30天 ,单位秒
    rememberMeMaxAge: 2592000
    kickout:
      kickoutUrl: /
    #默认
    credentialsMatcher:
      enable: true
      cacheName: credentialsMatcherCache
      hashAlgorithmName: MD5
      hashIterations: 6
      total: 6
    realms:
      - realmClass: com.lilianghui.commons.security.UserRealm
        authenticationCacheName: authenticationCache
      - realmClass: com.lilianghui.commons.security.StatelessRealm
        authenticationTokenClass: com.lilianghui.shiro.spring.starter.core.StatelessAuthenticationToken
        authenticationCacheName: authenticationTokenCache
        useDefaultMatcher: true
    filters:
      statelessAuthc: com.lilianghui.shiro.spring.starter.interceptor.StatelessAuthcFilter
    filterChainDefinitionMap: |
      /: anon
      /actuator/**: anon
      /login**: anon
      /resources/**: anon
      /logout**: logout
      /**: noSessionCreation,statelessAuthc
    filterChainDefinitionClass: com.lilianghui.commons.security.ChainDefinitionSectionMetaSource
    redisCache:
      shiroActiveSessionCache: 2h
      credentialsMatcherCache: 10m
      authenticationCache: 10m
#  redis:
#    cluster:
#      nodes: 10.250.209.89:7000,10.250.209.89:7001,10.250.209.89:7002,10.250.209.89:7003,10.250.209.89:7004,10.250.209.89:7005,10.250.209.89:7006
#      timeout: 2000
#      max-redirects: 7
#  cloud:
#    stream:
#      bindings:
#        springCloudBusInput:
#          content-type: application/json
#          destination: springCloudBus
#          binder: rocket1
#        springCloudBusOutput:
#          content-type: application/json
#          destination: springCloudBus
#          binder: rocket1
#      binders:
#        rocket1:
#          type: rocket
#      rocketmq:
#        binder:
#          nameSrvAddr: 127.0.0.1
#          default-name-srv-port: 9876
#        bindings:
#          springCloudBusOutput:
#            producer:
#              groupName: test
#          springCloudBusInput:
#            consumer:
#              groupName: test
  redis:
    password:
    database: 0
    host: llh
    port: 6379
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1
    timeout: 5000

#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest
  rocketmq:
    nameServer: llh:9876
    producer:
      group: producer-group
  p6spy:
    logFile: /home/${spring.application.name}/spy.log


# routes to serviceId
zuul:
  routes:
    fastdfs-server:
      path: /fastdfs/**
      serviceId: fastdfs-server
      stripPrefix: true
    elasticsearch-server:
      path: /elasticsearch/**
      serviceId: elasticsearch-server
      stripPrefix: true
    shiro-server:
      path: /shiro/**
      serviceId: shiro-server
      stripPrefix: true
  ignored-services: '*'
  ignoredPatterns: /**/**/index, /**/**/edit/**, /core/**, /**/**/copy/**, /pdf/*


security: false
management:
  endpoint:
    bus-refresh:
      enabled: true
  endpoints:
    shutdown:
      enabled: true
    health:
      sensitive: false
      show-details: always
    web:
      exposure:
        include: '*'

mybatis:
  configuration: com.lilianghui.spring.starter.mybatis.MyBatisConfiguration
  mapper-locations: classpath:/mapper/*.xml
  typeHandlersPackage: com.lilianghui.framework.mybatis.mapping
  jdbcTypeForNull: NULL
  mapUnderscoreToCamelCase: true


mapper:
  mappers:
  - com.lilianghui.framework.core.mapper.Mapper
  notEmpty: true
  resolveClass: com.lilianghui.framework.core.mapper.tk.resolve.DefaultEntityResolve
  entityScanPackages: com.lilianghui.entity
  enumerationHandlerClass: com.lilianghui.framework.mybatis.mapping.EnumerationHandler

redisson:
  address: llh:6379
  password:

gatway:
  name: llh
  age: 24