spring:
  mvc:
    static-path-pattern: /**
  thymeleaf:
    template-resolver-order: 0
  datasource:
    url: jdbc:p6spy:mysql://llh-tencent-os:3306/lvxin-agricultural-trade?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 1qaz@WSX
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
  shiro:
    login-url: /index
    success-url: /index
    cacheName: aa
    hashAlgorithmName: aa
    hashIterations: 6
    total: 6
    cacheManagerConfigFile:
    globalSessionTimeout: 6000
    sessionValidationInterval: 6000
    activeSessionsCacheName:
    cookieName:
    cipherKey:
    rememberMeCookieName:
    realms:
    rememberMeMaxAge: 1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    deserialization:
      fail-on-ignored-properties: false
      accept-empty-array-as-null-object: true
      accept-empty-string-as-null-object: true
    parser:
      allow-single-quotes: true
      allow-unquoted-field-names: true
      allow-unquoted-control-chars: true
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  config-location: classpath:/spring-mybatis-cfg.xml


mapper:
  mappers:
  - com.lilianghui.framework.core.mapper.Mapper
  notEmpty: true
  resolveClass: com.lilianghui.framework.core.mapper.tk.resolve.DefaultEntityResolve

rocketmq:
  group: transactional_message
  namesrvAddr: 127.0.0.1:9876
  instanceName: transactional_message
  topic: transactional_message
  tag: transactional_message
  entityBeanNameMap:
    com.lilianghui.entity.User: userService